### PR TITLE
Added loading indicator + example implementation

### PR DESCRIPTION
**Pull request by bellindj**

### CODE REVIEW

**Comment by ryanaklein** [comment]
What happens if i comment here

**Comment by bellindj** [comment]
@ryanaklein I agree the style needs some work but I can mess around with it later, I was just hoping to get something in there as a placeholder to help illustrate it is loading. What would be the advantage to using a protocol instead of a singleton?

**Comment by ryanaklein** [comment]
[Here's some general info about singletons](https://stackoverflow.com/questions/137975/what-is-so-bad-about-singletons)

There's just a lot of risk that comes along with them.

I think the main concern here is the tight coupling. If you change the code in the LoadingOverlay, every class that uses it is impacted. If you use a protocol you can have a default implementation and if there needs to be some special handling it can be overriden. 

It's just best to use protocols/interfaces in general. A good example of protocol oriented programing is how the login view controller works with the AWS protocols

**Comment by bellindj** [comment]
Thanks that makes sense - I will update the code to use a Protocol.

**Comment by bellindj** [comment]
@ryanaklein Updated to a protocol & extension... let me know if this is what you meant.

**Pull request closed without merging**
