### PR TITLE
Feature/loading indicator overkill

### PR DESCRIPTION
**Pull request by ryanaklein**
A few updates so that the implementing class doesn't really have to know anything about the protocol. Might be overkill on abstraction. What do you think, @bellindj?

### CODE REVIEW

**Comment by ryanaklein** [comment]
Also, wasn't sure if a new branch was the best way to go about this or not. I didn't feel i could express what I was going after in just comments

**Comment by bellindj** [comment]
That's nice - by adding that getter for the view you give the protocol access to the conformer's view. This will work for cases where we want the conformer's view to have the indicator, but what about when we want a specific cell that is a subclass of UIView to have a load indicator and overlay? I guess we could make another protocol that uses 'self.' Instead of 'view.' and have the cell's class implement that other protocol, but is that overkill versus passing in the view?

**Comment by ryanaklein** [comment]
We can just change the required property to loadingOverlayContainer and in the getter in the conforming class return whatever view we want

Thanks,
Ryan Klein
________________________________

**Comment by bellindj** [comment]
Good idea, that works for me!

**Pull request merged**
